import { useState, useEffect, useRef } from 'react';
import type { Profile } from '../../../types/profile';
import { getAllProfiles } from '../../profiles/profileStore';
import { ProfileSelector, getStoredProfileId } from './ProfileSelector';
import { ReplyCandidates } from './ReplyCandidates';
import { useReplyGeneration } from '../hooks/useReplyGeneration';
import './reply.css';

type Props = {
  transcriptionText: string;
};

export function ReplyScreen({ transcriptionText }: Props) {
  const [profiles, setProfiles] = useState<Profile[]>([]);
  // Initialise synchronously from localStorage so first auto-generation uses the stored profile
  const [selectedProfileId, setSelectedProfileId] = useState<string | null>(getStoredProfileId);
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    getAllProfiles()
      .then(all => {
        setProfiles(all);
        // If the stored ID is no longer valid, fall back to the first profile
        const storedId = getStoredProfileId();
        if (storedId && all.some(p => p.id === storedId)) {
          setSelectedProfileId(storedId);
        } else if (all.length > 0) {
          setSelectedProfileId(all[0].id);
        }
      })
      .catch(() => {
        // profiles load failure is non-fatal; reply generation still works without a profile
      });
  }, []);

  const selectedProfile = profiles.find(p => p.id === selectedProfileId) ?? null;
  const profileInstructions = selectedProfile?.instructions ?? '';

  const { replies, loading, error, regenerate } = useReplyGeneration(
    transcriptionText,
    profileInstructions,
  );

  // Auto-generate on first mount once we know the profile instructions
  useEffect(() => {
    if (!hasAutoGenerated.current && transcriptionText.trim()) {
      hasAutoGenerated.current = true;
      regenerate();
    }
  }, [transcriptionText, regenerate]);

  return (
    <main className="reply-page">
      <div className="reply-header">
        <h1>Reply suggestions</h1>
        <button
          className="btn btn-secondary btn-sm"
          onClick={regenerate}
          disabled={loading}
          aria-label="Regenerate reply suggestions"
        >
          ↺ Regenerate
        </button>
      </div>

      <ProfileSelector
        profiles={profiles}
        selectedId={selectedProfileId}
        onSelect={id => {
          setSelectedProfileId(id);
          // Trigger regeneration when profile changes
          regenerate();
        }}
      />

      {error && (
        <div className="reply-error" role="alert">
          {error}
        </div>
      )}

      <ReplyCandidates replies={replies} loading={loading} />
    </main>
  );
}
